
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Enjel Rupiani
 */
public class storyuu extends javax.swing.JFrame {
    int reguler,ultra,gold,price,buy,total,payment,change;

    /**
     * Creates new form storyuu
     */
    public storyuu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seat = new javax.swing.JComboBox<>();
        rb_reguler = new javax.swing.JRadioButton();
        rb_ultraxd = new javax.swing.JRadioButton();
        rb_gold = new javax.swing.JRadioButton();
        txt_price = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_purchaseamount = new javax.swing.JTextField();
        txt_totalpay = new javax.swing.JTextField();
        txt_change = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        btn_input = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_exit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Movie Ticket Reservation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 320, 27);

        jLabel2.setBackground(new java.awt.Color(102, 51, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Seat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 71, 40, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Ticket Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 112, 90, 20);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(27, 433, 0, 0);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Unit Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(27, 170, 80, 29);

        seat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        seat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A", "B", "C", "D", " " }));
        seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatActionPerformed(evt);
            }
        });
        getContentPane().add(seat);
        seat.setBounds(120, 70, 72, 22);

        rb_reguler.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rb_reguler.setText("Regular");
        rb_reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_regulerActionPerformed(evt);
            }
        });
        getContentPane().add(rb_reguler);
        rb_reguler.setBounds(120, 110, 80, 21);

        rb_ultraxd.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rb_ultraxd.setText("Ultra XD");
        rb_ultraxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ultraxdActionPerformed(evt);
            }
        });
        getContentPane().add(rb_ultraxd);
        rb_ultraxd.setBounds(200, 110, 80, 21);

        rb_gold.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rb_gold.setText("Gold");
        rb_gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_goldActionPerformed(evt);
            }
        });
        getContentPane().add(rb_gold);
        rb_gold.setBounds(120, 140, 70, 21);
        getContentPane().add(txt_price);
        txt_price.setBounds(120, 180, 95, 22);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchasing Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Customer  Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Purchase Amount");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Total Pay");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Change");

        txt_purchaseamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_purchaseamountActionPerformed(evt);
            }
        });
        txt_purchaseamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_purchaseamountKeyReleased(evt);
            }
        });

        txt_totalpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalpayActionPerformed(evt);
            }
        });

        txt_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_changeActionPerformed(evt);
            }
        });
        txt_change.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_changeKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Payment");

        txt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paymentActionPerformed(evt);
            }
        });
        txt_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paymentKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_totalpay, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(txt_purchaseamount)
                    .addComponent(txt_name)
                    .addComponent(txt_change)
                    .addComponent(txt_payment))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_purchaseamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_totalpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(6, 227, 290, 220);

        btn_input.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_input.setText("Input Data");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        getContentPane().add(btn_input);
        btn_input.setBounds(304, 68, 100, 23);

        btn_print.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_print.setText("Print Data");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print);
        btn_print.setBounds(489, 68, 84, 23);

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 110, 252, 286);

        btn_exit.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(411, 68, 72, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 660, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_ultraxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ultraxdActionPerformed
        // TODO add your handling code here:
        //displays the price after selecting the ticket type
        //ultra xd
        if(rb_ultraxd.isSelected())
        {
            txt_price.setText(String.valueOf(ultra));
        }
    }//GEN-LAST:event_rb_ultraxdActionPerformed

    private void seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatActionPerformed
        // TODO add your handling code here:
        //menentukan harga untuk setiap seat
        if(seat.getSelectedItem().equals("pilih seat"))
        {
        buttonGroup1.clearSelection();
        txt_price.setText("");
        }
        else if(seat.getSelectedItem().equals("A"))
        {
        reguler=50000;
        ultra=70000;
        gold=90000;
        {
        }
        }
        else if(seat.getSelectedItem().equals("B"))
        {
        reguler=45000;
        ultra=65000;
        gold=85000;   
        }
        else if(seat.getSelectedItem().equals("C"))
        {
        reguler=40000;
        ultra=60000;
        gold=80000;
        }
        else if(seat.getSelectedItem().equals("D"))
        {
        reguler=35000;
        ultra=55000;
        gold=75000;
        }
        
    }//GEN-LAST:event_seatActionPerformed

    private void rb_regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_regulerActionPerformed
        // TODO add your handling code here:
        //displays the price after selecting the ticket type
        //reguler
        if(rb_reguler.isSelected())
        {
            txt_price.setText(String.valueOf(reguler));
        }
    }//GEN-LAST:event_rb_regulerActionPerformed

    private void rb_goldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_goldActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //displays the price after selecting the ticket type
        //gold
        if(rb_gold.isSelected())
        {
            txt_price.setText(String.valueOf(gold));
        }
        
        
    }//GEN-LAST:event_rb_goldActionPerformed

    private void txt_purchaseamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_purchaseamountActionPerformed
        // TODO add your handling code here:
        //input the total of ticket and the total pay
        buy=Integer.parseInt(txt_purchaseamount.getText());
        price=Integer.parseInt(txt_price.getText());
        total=payment*price;
        txt_totalpay.setText(String.valueOf(total));
               
    }//GEN-LAST:event_txt_purchaseamountActionPerformed

    private void txt_totalpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalpayActionPerformed
        // TODO add your handling code here:
        //input the purchase amount and the total payment
        total=Integer.parseInt(txt_totalpay.getText());
        change=Integer.parseInt(txt_totalpay.getText());
        total=total-change;
        txt_change.setText(String.valueOf(total));
               
        
    }//GEN-LAST:event_txt_totalpayActionPerformed

    private void txt_purchaseamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_purchaseamountKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txt_price.getText());
        b=Integer.valueOf(txt_purchaseamount.getText());
        c=a*b;
        txt_totalpay.setText(""+c);
        
    }//GEN-LAST:event_txt_purchaseamountKeyReleased

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null,"you will exit","exit",JOptionPane.OK_OPTION );
        if(answer==JOptionPane.OK_OPTION) 
        {
            dispose();
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paymentActionPerformed
        // TODO add your handling code here:
        //input the total of ticket and the total payment
        payment=Integer.parseInt(txt_payment.getText());
        change=Integer.parseInt(txt_totalpay.getText());
        total=payment-change;
        txt_change.setText(String.valueOf(total));
        
    }//GEN-LAST:event_txt_paymentActionPerformed

    private void txt_paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyReleased
        // TODO add your handling code here:
          int a,b,c;
        a=Integer.valueOf(txt_payment.getText());
        b=Integer.valueOf(txt_totalpay.getText());
        c=a-b;
        txt_change.setText(""+c);
        
    }//GEN-LAST:event_txt_paymentKeyReleased

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        txt_price.setText("");
        seat.setSelectedItem("Select Ticket Type");
        txt_name.setText("");
        txt_totalpay.setText("");
        txt_purchaseamount.setText("");
        txt_payment.setText("");
        txt_change.setText("");
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        btn_print.setText((String)seat.getSelectedItem());
        txt_area.setText(
        "Customer Name    :"+txt_name.getText()+"\n"+
        "Purchase Amount  :"+txt_purchaseamount.getText()+"\n"+
        "Total Pay        :"+txt_totalpay.getText()+"\n"+
        "Payment          :"+txt_payment.getText()+"\n"+   
        "Change           :"+txt_change.getText()+"\n");
                
                
      
    }//GEN-LAST:event_btn_printActionPerformed

    private void txt_changeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_changeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_changeKeyReleased

    private void txt_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_changeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(storyuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(storyuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(storyuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(storyuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new storyuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_print;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_gold;
    private javax.swing.JRadioButton rb_reguler;
    private javax.swing.JRadioButton rb_ultraxd;
    private javax.swing.JComboBox<String> seat;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_change;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_purchaseamount;
    private javax.swing.JTextField txt_totalpay;
    // End of variables declaration//GEN-END:variables
}
